language: node_js

node_js:
  - node

branches:
  only:
    - master
before_script:
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli
  - npm cache clean

script:
  - ng build --prod --debug

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive --debug

notifications:
  email:
    on_failure: change
    on_success: change
